name: Full Refresh Youtube Stage Tables

on:
  workflow_dispatch:       # Allows manual run from the Actions tab

jobs:
  run_full_refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full refresh script
        env:
          DBL_URL: ${{ secrets.NEON_DBL_URL }}
          YI_API_KEY: ${{ secrets.YI_API_KEY }}
          CHANNEL_KEY: ${{ secrets.CHANNEL_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: |
          python data_preprocessing/youtube_data_api_full_refresh.py
          python data_preprocessing/youtube_day_analytics_api_full_refresh.py
