name: Weekly Incremental Update

on:
  schedule:
    - cron: '0 9 * * 4'   # Every Thursday at 09:00 UTC
  workflow_dispatch:       # Allows manual run from the Actions tab

jobs:
  run_incremental_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run incremental script
        env:
          DBL_URL: ${{ secrets.NEON_DBL_URL }}
          YI_API_KEY: ${{ secrets.YI_API_KEY }}
          CHANNEL_KEY: ${{ secrets.CHANNEL_KEY }}
        run: |
          python data_preprocessing/youtube_data_api_incremental.py
